# Generated by Django 4.1.7 on 2023-03-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
